---
TODO: collect static
TODO: create version meta file

- name: Collect Static
  become: yes
  become_user: openslides
  command: "{{ openslides_bin }} collectstatic --pythonpath {{ openslides_settings_path }} --settings settings --noinput"
  args:
    creates: "{{ openslides_user_data_path }}/collected_static/css"
