galaxy_info:
  author: Oskar Hahn
  description: Look for ostcar

  license: MIT

  min_ansible_version: 2.0

  platforms:
  - name: Ubuntu
    versions:
    - xenial
  - name: Archlinux


  galaxy_tags:
  - server

dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
