---
- name: Creates directory
  file: path="{{ openslides_instance_path }}" state=directory

- name: Creates data directory
  file: path="{{ openslides_instance_path }}/data" state=directory

- name: Create Settings
  template:
    dest: "{{ openslides_instance_path }}/settings.py"
    src: settings.py.j2
