---
- name: Create nginx vhost config
  when: openslides_nginx_domains
  become: yes
  template:
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    src: nginx_instance.conf.j2
  notify:
  - Restart nginx
  with_items: "{{ openslides_nginx_domains }}"

