---
- name: Create systemd units for openslides
  become: yes
  register: createServices
  template:
    dest: /etc/systemd/system/openslides_instance_{{ instance_id }}.service
    src: "openslides_instance.service.j2"

- name: Create nginx service unit for socket activation
  when: openslides_nginx_socket_activation
  become: yes
  register: createNginxService
  template:
    dest: /etc/systemd/system/openslides_instance_{{ instance_id }}.socket
    src: openslides_instance.socket

- name: Start and enalbe openslides
  become: yes
  service:
    name: openslides_instance_{{ instance_id }}.service
    enabled: yes
    state: started

- name: Start and enalbe nginx via socket activation
  when: openslides_nginx_socket_activation
  become: yes
  service:
    name: openslides_instance_{{ instance_id }}.socket
    enabled: yes
    state: started

