---
#- TODO: run migration
#- TODO: add admin user

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  sudo_user: postgres
  postgresql_db: name=openslides_db_{{ instance_id }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 login_host={{ postgres_host }}
                 login_user={{ postgres_user }}
                 login_password={{ postgres_password }}
                 state=present

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db=openslides_db_{{ instance_id }}
                   name=openslides_db_{{ instance_id }}
                   password={{ openslides_instance_db_password }}
                   login_host={{ postgres_host }}
                   login_user={{ postgres_user }}
                   login_password={{ postgres_password }}
                   priv=ALL
                   state=present

#- TODO: add_configuration

- name: Migrate Database
  become: yes
  become_user: openslides
  register: openslidesMigratedDatabase
  command: "{{ openslides_bin }} migrate --pythonpath {{ openslides_settings_path }} --settings settings --noinput"
  args:
    creates: "{{ openslides_user_data_path }}/database.sqlite"

- name: Activate anonymous user
  when: openslidesMigratedDatabase.changed
  become: yes
  shell: echo "from openslides.core.config import config;config['general_system_enable_anonymous']=True" | {{ openslides_bin }} shell --pythonpath {{ openslides_settings_path }} --settings settings

