---
- name: Check variable openslides_secure_key
  when: not openslides_secure_key
  fail:
    msg: The variable openslides_secure_key is not set.

- name: Create instance container
  include: create_container.yml

- name: Initialize database
  include: init_instance_database.yml

- name: Create systemd units
  include: create_units.yml

- name: Create nginx configuration
  include: create_nginx_conf.yml

