---
- name: Setup ubuntu 16.04
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"
  include: ubuntu16.04.yml

- name: Setup Archlinux
  when: ansible_distribution == "Archlinux"
  include: archlinux.yml

- name: Check Setup
  when: not openslides_distro_fround
  fail:
    msg: openslides_distro_fround

- name: Create user openslides
  become: yes
  user:
    name: openslides
    system: yes
    createhome: no
    state: present

- name: Install openslides from pypi
  when: not openslides_use_git
  become: yes
  pip:
    name: openslides
    executable: "{{ pip_executable }}"
    state: present

- name: Create directory for openslides_repo
  when: openslides_use_git
  become: yes
  file:
    path: /var/cache/openslides_repo
    state: directory
    owner: openslides

- name: Create home directory for user openslides, npm needs it...
  when: openslides_use_git
  become: yes
  file:
    path: /home/openslides
    state: directory
    owner: openslides

- name: Checkout openslides repo
  when: openslides_use_git
  become: yes
  become_user: openslides
  register: OpenSlidesGit
  git:
    repo: "{{ openslides_git_repo }}"
    dest: /var/cache/openslides_repo
    version: "{{ openslides_git_branch }}"

- name: Install npm deps
  when: openslides_use_git and OpenSlidesGit.changed
  become: yes
  become_user: openslides
  become_method: su  # TO make ubuntu happy
  npm:
    path: /var/cache/openslides_repo
    ignore_scripts: yes  # There seems to be a problem on ubuntu with our scripts

- name: Install bower deps
  when: openslides_use_git and OpenSlidesGit.changed
  become: yes
  become_user: openslides
  become_method: su  # TO make ubuntu happy
  bower:
    path: /var/cache/openslides_repo
    relative_execpath: node_modules/.bin

- name: Call gulp
  when: openslides_use_git and OpenSlidesGit.changed
  become: yes
  become_user: openslides
  become_method: su  # TO make ubuntu happy
  command: /var/cache/openslides_repo/node_modules/.bin/gulp
  args:
    chdir: /var/cache/openslides_repo/
  
- name: Install openslides from repo
  when: openslides_use_git and OpenSlidesGit.changed
  become: yes
  pip:
    name: file:///var/cache/openslides_repo
    executable: "{{ pip_executable }}"
    state: latest

- name: Install asgi_redis via pip
  become: yes
  pip:
    name: asgi_redis
    executable: "{{ pip_executable }}"
    state: present

- name: Create settings path
  become: yes
  file:
    path: "{{ openslides_settings_path }}"
    state: directory
    mode: 0755

- name: create user data path
  become: yes
  file:
    path: "{{ openslides_user_data_path }}"
    state: directory
    mode: 0755
    owner: openslides

- name: create user data path
  become: yes
  file:
    path: "{{ log_dir }}"
    state: directory
    mode: 0755
    owner: openslides

- name: Create supervisor config
  become: yes
  template:
    dest: "/etc/supervisord.conf"
    src: supervisord.conf.j2
